# ===== 输出模式与 SYN6288 UART 传输 =====
# 生产路径为 a1_uart + 固定 GBK 帧。ACK/主动 busy 查询默认关闭，是因为当前
# 载板回传不稳定；被动 RX 只用于统计，不作为持续播报的硬前提。
export A1_OUTPUT_MODE="${A1_OUTPUT_MODE:-both}"
export A1_VOICE_ENABLE="${A1_VOICE_ENABLE:-1}"
export A1_VOICE_BACKEND="${A1_VOICE_BACKEND:-a1_uart}"
export A1_VOICE_BAUD="${A1_VOICE_BAUD:-9600}"
export A1_VOICE_INTERVAL_FRAMES="${A1_VOICE_INTERVAL_FRAMES:-1}"
export A1_VOICE_STABLE_FRAMES="${A1_VOICE_STABLE_FRAMES:-1}"
export A1_VOICE_CLEAR_STABLE_FRAMES="${A1_VOICE_CLEAR_STABLE_FRAMES:-3}"
export A1_VOICE_COOLDOWN_MS="${A1_VOICE_COOLDOWN_MS:-0}"
export A1_VOICE_CLEAR_REPEAT_MS="${A1_VOICE_CLEAR_REPEAT_MS:-0}"
export A1_VOICE_STOP_REPEAT_MS="${A1_VOICE_STOP_REPEAT_MS:-500}"
export A1_VOICE_FAULT_REPEAT_MS="${A1_VOICE_FAULT_REPEAT_MS:-0}"
export A1_VOICE_FAULT_HOLD_MS="${A1_VOICE_FAULT_HOLD_MS:-2500}"
export A1_VOICE_SWITCH_MIN_MS="${A1_VOICE_SWITCH_MIN_MS:-0}"
export A1_VOICE_TX_GAP_MS="${A1_VOICE_TX_GAP_MS:-0}"
export A1_VOICE_STOP_FOLLOWUP_HOLD_MS="${A1_VOICE_STOP_FOLLOWUP_HOLD_MS:-0}"
export A1_VOICE_TURN_FOLLOWUP_HOLD_MS="${A1_VOICE_TURN_FOLLOWUP_HOLD_MS:-0}"
export A1_VOICE_PRE_STOP="${A1_VOICE_PRE_STOP:-0}"
export A1_VOICE_ACK="${A1_VOICE_ACK:-0}"
export A1_VOICE_REQUIRE_ACK="${A1_VOICE_REQUIRE_ACK:-0}"
export A1_VOICE_QUERY_IDLE="${A1_VOICE_QUERY_IDLE:-0}"
export A1_VOICE_FIXED_FRAME="${A1_VOICE_FIXED_FRAME:-1}"
export A1_VOICE_USE_PREFIX="${A1_VOICE_USE_PREFIX:-0}"
export A1_VOICE_REOPEN_EACH_TX="${A1_VOICE_REOPEN_EACH_TX:-0}"
export A1_VOICE_BYTE_GAP_US="${A1_VOICE_BYTE_GAP_US:-2000}"
export A1_VOICE_POST_TX_DELAY_MS="${A1_VOICE_POST_TX_DELAY_MS:-30}"
export A1_VOICE_PASSIVE_RX="${A1_VOICE_PASSIVE_RX:-1}"
# Keep transaction diagnostics enabled for this board-validation image. It
# prints one TX/DONE pair per spoken word without detector-level debug output.
export A1_VOICE_DIAG="${A1_VOICE_DIAG:-1}"
export A1_VOICE_PASSIVE_RX_MS="${A1_VOICE_PASSIVE_RX_MS:-80}"
export A1_VOICE_ACK_TIMEOUT_MS="${A1_VOICE_ACK_TIMEOUT_MS:-200}"
export A1_VOICE_PLAY_TIMEOUT_MS="${A1_VOICE_PLAY_TIMEOUT_MS:-3000}"
export A1_VOICE_ACTION_PROMPT_MS="${A1_VOICE_ACTION_PROMPT_MS:-1000}"
export A1_VOICE_INTER_FRAME_MS="${A1_VOICE_INTER_FRAME_MS:-12}"
export A1_VOICE_RX_POLL_MS="${A1_VOICE_RX_POLL_MS:-3}"
export A1_VOICE_IDLE_TIMEOUT_MS="${A1_VOICE_IDLE_TIMEOUT_MS:-180}"
export A1_VOICE_RECOVER_WAIT_MS="${A1_VOICE_RECOVER_WAIT_MS:-1000}"
export A1_VOICE_RETRY="${A1_VOICE_RETRY:-0}"
export A1_VOICE_WAIT_IDLE_MS="${A1_VOICE_WAIT_IDLE_MS:-1200}"
export A1_VOICE_TEST_ON_START="${A1_VOICE_TEST_ON_START:-0}"
export A1_VOICE_SELFTEST="${A1_VOICE_SELFTEST:-0}"

# ===== 后处理、串口摘要与异常恢复 =====
export A1_DEBUG_POSTPROCESS="${A1_DEBUG_POSTPROCESS:-0}"
export A1_DEBUG_POSTPROCESS_INTERVAL="${A1_DEBUG_POSTPROCESS_INTERVAL:-60}"
export A1_OUTPUT_SERIAL_DIAG="${A1_OUTPUT_SERIAL_DIAG:-0}"
export A1_OUTPUT_INTERVAL_FRAMES="${A1_OUTPUT_INTERVAL_FRAMES:-1}"
export A1_NAV_HEARTBEAT_MS="${A1_NAV_HEARTBEAT_MS:-2000}"
export A1_NAV_MIN_CHANGE_MS="${A1_NAV_MIN_CHANGE_MS:-500}"
export A1_CAPTURE_AUTO_RESTART="${A1_CAPTURE_AUTO_RESTART:-1}"
export A1_COVER_BLACK_MEAN_MAX="${A1_COVER_BLACK_MEAN_MAX:-45}"
export A1_COVER_BLACK_RATIO_PCT="${A1_COVER_BLACK_RATIO_PCT:-80}"
export A1_COVER_TRIGGER_FRAMES="${A1_COVER_TRIGGER_FRAMES:-3}"
export A1_COVER_RECOVERY_FRAMES="${A1_COVER_RECOVERY_FRAMES:-18}"

# ===== SC132GS 全画面采集与交替双 ROI =====
# online pipeline 保留完整 720x1280；模型在 CPU/NPU 预处理阶段交替观察
# y=0..720 与 y=560..1280，两视图重叠 160 像素且每帧仍只推理一次。
export A1_FULL_FRAME_WIDTH="${A1_FULL_FRAME_WIDTH:-720}"
export A1_FULL_FRAME_HEIGHT="${A1_FULL_FRAME_HEIGHT:-1280}"
export A1_CAPTURE_WIDTH="${A1_CAPTURE_WIDTH:-720}"
export A1_CAPTURE_HEIGHT="${A1_CAPTURE_HEIGHT:-1280}"
export A1_CAPTURE_CROP_X0="${A1_CAPTURE_CROP_X0:-0}"
export A1_CAPTURE_CROP_Y0="${A1_CAPTURE_CROP_Y0:-0}"
export A1_DUAL_ROI="${A1_DUAL_ROI:-1}"
export A1_ROI_UPPER_Y="${A1_ROI_UPPER_Y:-0}"
export A1_ROI_LOWER_Y="${A1_ROI_LOWER_Y:-560}"

# ===== head6 候选、NMS、OSD 和性能统计 =====
export A1_NMS_TOP_K="${A1_NMS_TOP_K:-300}"
export A1_NMS_KEEP_TOP_K="${A1_NMS_KEEP_TOP_K:-40}"
export A1_OSD_INTERVAL_FRAMES="${A1_OSD_INTERVAL_FRAMES:-2}"
export A1_PERF_INTERVAL_FRAMES="${A1_PERF_INTERVAL_FRAMES:-60}"
export A1_SENSOR_FPS="${A1_SENSOR_FPS:-90}"

# ===== One-model indoor detection + scene/depth/stair perception =====
export A1_MODEL_PATH="${A1_MODEL_PATH:-/app_demo/app_assets/models/graynav_unified_indoor8_scene21.m1model}"
export A1_SURFACE_STALE_MS="${A1_SURFACE_STALE_MS:-1000}"
export A1_MODEL_OUTPUT_LAYOUT="${A1_MODEL_OUTPUT_LAYOUT:-HWC}"
export A1_YOLO_DYNAMIC_ALLOC="${A1_YOLO_DYNAMIC_ALLOC:-0}"

# ===== 相机安装参数、测距不确定度与三走廊规划 =====
export A1_CAM_FOV_H_DEG="${A1_CAM_FOV_H_DEG:-49.7}"
export A1_CAM_FOV_V_DEG="${A1_CAM_FOV_V_DEG:-78.9}"
export A1_CAM_HEIGHT_M="${A1_CAM_HEIGHT_M:-0.71}"
export A1_CAM_PITCH_DOWN_DEG="${A1_CAM_PITCH_DOWN_DEG:-15.0}"
export A1_GROUND_CONTACT_OFFSET_RATIO="${A1_GROUND_CONTACT_OFFSET_RATIO:-0.012}"
# 现场 4~5m 目标低估为 2~3m 后的保守首轮比例修正；仍需用已知距离复核。
export A1_RANGE_GEOMETRY_SCALE="${A1_RANGE_GEOMETRY_SCALE:-1.60}"
export A1_RANGE_SIZE_SCALE="${A1_RANGE_SIZE_SCALE:-1.00}"
export A1_RANGE_SAFETY_SCALE="${A1_RANGE_SAFETY_SCALE:-1.00}"
export A1_RANGE_URGENT_M="${A1_RANGE_URGENT_M:-0.85}"
export A1_RANGE_NEAR_M="${A1_RANGE_NEAR_M:-1.25}"
export A1_RANGE_WARNING_M="${A1_RANGE_WARNING_M:-2.20}"
export A1_SIDE_CLEAR_M="${A1_SIDE_CLEAR_M:-1.45}"
export A1_TURN_MARGIN_M="${A1_TURN_MARGIN_M:-0.25}"
export A1_SECTOR_LEFT_BOUND="${A1_SECTOR_LEFT_BOUND:-0.35}"
export A1_SECTOR_RIGHT_BOUND="${A1_SECTOR_RIGHT_BOUND:-0.65}"
export A1_WIDE_BOX_RATIO="${A1_WIDE_BOX_RATIO:-0.88}"
export A1_CENTER_HALF_WIDTH_M="${A1_CENTER_HALF_WIDTH_M:-0.22}"
# blocked_surface 结果保留诊断，但默认不参与动作，避免地面误分导致持续减速。
export A1_ENABLE_WALL_GUIDANCE="${A1_ENABLE_WALL_GUIDANCE:-0}"

# ===== 仅在暗光且仍有纹理时启用的局部灰度增强 =====
# The unified model was trained with grayscale photometric augmentation. Keep
# sensor pixels unchanged for the first board qualification; enable the LUT
# only as a controlled dark-room experiment after the baseline is recorded.
export A1_ADAPTIVE_GRAY="${A1_ADAPTIVE_GRAY:-0}"
export A1_ADAPTIVE_GRAY_DARK_MEAN="${A1_ADAPTIVE_GRAY_DARK_MEAN:-75}"
export A1_ADAPTIVE_GRAY_BLEND="${A1_ADAPTIVE_GRAY_BLEND:-60}"
export A1_ADAPTIVE_GRAY_BRIGHT_MEAN="${A1_ADAPTIVE_GRAY_BRIGHT_MEAN:-195}"
export A1_ADAPTIVE_GRAY_DIAG="${A1_ADAPTIVE_GRAY_DIAG:-0}"

chmod +x ./ssne_ai_demo
# ===== 进程监督 =====
# 正常退出不重启；采集/推理持续故障以非零码退出后，最多退避重启五次。
restart_count=0
while true; do
    ./ssne_ai_demo
    code=$?
    [ "$code" -eq 0 ] && exit 0
    restart_count=$((restart_count + 1))
    echo "[SUPERVISOR][WARN] app exited code=$code restart=$restart_count"
    [ "$restart_count" -ge 5 ] && exit "$code"
    sleep "$restart_count"
done
