#!/bin/sh

chmod +x ./ssne_ai_demo

# Default hardware route for the official A1 UART API:
#   A1 UART_TX0: P4 pin 15 (A1_D0_UART0TX) -> level shifter LV input -> SYN6288 RXD
#   A1 UART_RX0: P4 pin 16 (A1_D2_UART0RX) <- level shifter LV output <- SYN6288 TXD, optional
#   GND:         P4 pin 33/34/47/48         -> SYN6288 GND and 5 V supply GND
#
# Backup tty route for debugging, if you intentionally use UART1 pins:
#   A1 UART1 TX: P4 pin 4  (A1_D1_UART1TX) -> level shifter -> SYN6288 RXD
#   A1 UART1 RX: P4 pin 6  (A1_D3_UART1RX) <- level shifter <- SYN6288 TXD, optional
# Confirm the Linux device node on the board with:
#   ls -l /dev/ttyS* /dev/ttyAMA* 2>/dev/null
# Then run with A1_VOICE_BACKEND=tty and override A1_VOICE_UART if needed.

export A1_OUTPUT_MODE="${A1_OUTPUT_MODE:-both}"
export A1_VOICE_BACKEND="${A1_VOICE_BACKEND:-a1_uart}"
export A1_VOICE_UART="${A1_VOICE_UART:-/dev/ttyS1}"
export A1_VOICE_BAUD="${A1_VOICE_BAUD:-9600}"
export A1_VOICE_INTERVAL_FRAMES="${A1_VOICE_INTERVAL_FRAMES:-2}"
export A1_VOICE_STABLE_FRAMES="${A1_VOICE_STABLE_FRAMES:-2}"
export A1_VOICE_CLEAR_STABLE_FRAMES="${A1_VOICE_CLEAR_STABLE_FRAMES:-3}"
export A1_VOICE_COOLDOWN_MS="${A1_VOICE_COOLDOWN_MS:-1200}"
export A1_VOICE_CLEAR_REPEAT_MS="${A1_VOICE_CLEAR_REPEAT_MS:-1200}"
export A1_VOICE_STOP_REPEAT_MS="${A1_VOICE_STOP_REPEAT_MS:-1200}"
export A1_VOICE_SWITCH_MIN_MS="${A1_VOICE_SWITCH_MIN_MS:-0}"
export A1_VOICE_TX_GAP_MS="${A1_VOICE_TX_GAP_MS:-800}"
export A1_VOICE_PRE_STOP="${A1_VOICE_PRE_STOP:-0}"
export A1_VOICE_ACK="${A1_VOICE_ACK:-0}"
export A1_VOICE_REQUIRE_ACK="${A1_VOICE_REQUIRE_ACK:-0}"
export A1_VOICE_QUERY_IDLE="${A1_VOICE_QUERY_IDLE:-0}"
export A1_VOICE_FIXED_FRAME="${A1_VOICE_FIXED_FRAME:-1}"
export A1_VOICE_USE_PREFIX="${A1_VOICE_USE_PREFIX:-0}"
export A1_VOICE_REOPEN_EACH_TX="${A1_VOICE_REOPEN_EACH_TX:-1}"
export A1_VOICE_BYTE_GAP_US="${A1_VOICE_BYTE_GAP_US:-1000}"
export A1_VOICE_POST_TX_DELAY_MS="${A1_VOICE_POST_TX_DELAY_MS:-30}"
export A1_VOICE_PASSIVE_RX="${A1_VOICE_PASSIVE_RX:-1}"
export A1_VOICE_DIAG="${A1_VOICE_DIAG:-0}"
export A1_VOICE_PASSIVE_RX_MS="${A1_VOICE_PASSIVE_RX_MS:-80}"
export A1_VOICE_NO_RX_RECOVER="${A1_VOICE_NO_RX_RECOVER:-5}"
export A1_VOICE_SOFT_RESET_EVERY_TX="${A1_VOICE_SOFT_RESET_EVERY_TX:-20}"
export A1_VOICE_ACK_TIMEOUT_MS="${A1_VOICE_ACK_TIMEOUT_MS:-500}"
export A1_VOICE_IDLE_TIMEOUT_MS="${A1_VOICE_IDLE_TIMEOUT_MS:-180}"
export A1_VOICE_RECOVER_WAIT_MS="${A1_VOICE_RECOVER_WAIT_MS:-1000}"
export A1_VOICE_RETRY="${A1_VOICE_RETRY:-0}"
export A1_VOICE_TEST_ON_START="${A1_VOICE_TEST_ON_START:-0}"
export A1_VOICE_SELFTEST="${A1_VOICE_SELFTEST:-0}"
export A1_DEBUG_POSTPROCESS="${A1_DEBUG_POSTPROCESS:-0}"
export A1_DEBUG_POSTPROCESS_INTERVAL="${A1_DEBUG_POSTPROCESS_INTERVAL:-60}"
export A1_OUTPUT_SERIAL_DIAG="${A1_OUTPUT_SERIAL_DIAG:-0}"
export A1_OUTPUT_INTERVAL_FRAMES="${A1_OUTPUT_INTERVAL_FRAMES:-5}"
export A1_CAPTURE_AUTO_RESTART="${A1_CAPTURE_AUTO_RESTART:-1}"
export A1_FULL_FRAME_WIDTH="${A1_FULL_FRAME_WIDTH:-720}"
export A1_FULL_FRAME_HEIGHT="${A1_FULL_FRAME_HEIGHT:-1280}"
export A1_CAPTURE_WIDTH="${A1_CAPTURE_WIDTH:-720}"
export A1_CAPTURE_HEIGHT="${A1_CAPTURE_HEIGHT:-1280}"
export A1_CAPTURE_CROP_X0="${A1_CAPTURE_CROP_X0:-0}"
export A1_CAPTURE_CROP_Y0="${A1_CAPTURE_CROP_Y0:-0}"
export A1_DUAL_ROI="${A1_DUAL_ROI:-1}"
export A1_ROI_UPPER_Y="${A1_ROI_UPPER_Y:-0}"
export A1_ROI_LOWER_Y="${A1_ROI_LOWER_Y:-560}"
export A1_NMS_TOP_K="${A1_NMS_TOP_K:-300}"
export A1_NMS_KEEP_TOP_K="${A1_NMS_KEEP_TOP_K:-40}"
export A1_OSD_INTERVAL_FRAMES="${A1_OSD_INTERVAL_FRAMES:-2}"
export A1_PERF_INTERVAL_FRAMES="${A1_PERF_INTERVAL_FRAMES:-60}"
export A1_SENSOR_FPS="${A1_SENSOR_FPS:-90}"
export A1_CAM_FOV_H_DEG="${A1_CAM_FOV_H_DEG:-49.7}"
export A1_CAM_FOV_V_DEG="${A1_CAM_FOV_V_DEG:-78.9}"
export A1_CAM_HEIGHT_M="${A1_CAM_HEIGHT_M:-0.85}"
export A1_CAM_PITCH_DOWN_DEG="${A1_CAM_PITCH_DOWN_DEG:-15.0}"

restart_count=0
while true; do
    ./ssne_ai_demo
    code=$?
    [ "$code" -eq 0 ] && exit 0
    restart_count=$((restart_count + 1))
    echo "[SUPERVISOR][WARN] app exited code=$code restart=$restart_count"
    [ "$restart_count" -ge 5 ] && exit "$code"
    sleep "$restart_count"
done
